# Generated by Django 3.2.12 on 2022-02-22 17:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageStructure', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebPageSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('queryParams', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None)),
                ('pageStructure', models.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('webPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectDataAPI.webpage')),
            ],
        ),
        migrations.AddField(
            model_name='webpage',
            name='webSite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectDataAPI.website'),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('webSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectDataAPI.website')),
            ],
        ),
    ]
