# Generated by Django 3.2.12 on 2022-04-12 10:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPageIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageStructure', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebPageSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('queryParams', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None)),
                ('pageStructure', models.JSONField()),
                ('similarity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('webPageIdentifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectDataAPI.webpageidentifier')),
                ('webSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectDataAPI.website')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(unique=True)),
                ('webSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectDataAPI.website')),
            ],
        ),
    ]
