# Generated by Django 3.2.12 on 2022-04-16 09:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('queryParams', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None)),
                ('pageStructure', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebPageIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageStructure', models.JSONField()),
                ('similarityMethod', models.CharField(choices=[('1', 'LCS'), ('2', 'APTED'), ('3', 'LCS_Optimized'), ('4', 'APTED_Optimized')], default='3', max_length=2)),
                ('webPages', models.ManyToManyField(through='CollectDataAPI.Matching', to='CollectDataAPI.WebPage')),
            ],
        ),
        migrations.AddField(
            model_name='webpage',
            name='webSite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectDataAPI.website'),
        ),
        migrations.AddField(
            model_name='matching',
            name='webPage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectDataAPI.webpage'),
        ),
        migrations.AddField(
            model_name='matching',
            name='webPageIdentifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectDataAPI.webpageidentifier'),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(unique=True)),
                ('webSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectDataAPI.website')),
            ],
        ),
    ]
