# Generated by Django 3.2.12 on 2022-02-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectDataAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='webpagespecification',
            name='url',
            field=models.URLField(),
        ),
    ]
