# Generated by Django 3.2.12 on 2022-04-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('CollectDataAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebPageSpecification',
            new_name='WebPage',
        ),
    ]
