# Generated by Django 4.0.1 on 2022-02-13 17:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectDataAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='query_params',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
    ]
