# Generated by Django 3.2.12 on 2022-04-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollectDataAPI', '0002_auto_20220416_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='queryParams',
        ),
    ]
