# Generated by Django 3.2.12 on 2022-04-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectDataAPI', '0002_rename_webpagespecification_webpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='similarity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
