# Generated by Django 3.2.12 on 2022-03-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectDataAPI', '0002_auto_20220225_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpagespecification',
            name='similarity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webpage',
            name='pageStructure',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='webpagespecification',
            name='pageStructure',
            field=models.TextField(),
        ),
    ]
