# Generated by Django 3.2.12 on 2022-02-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollectDataAPI', '0002_data_query_params'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='url',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='query_params',
            new_name='queryParams',
        ),
    ]
