# Generated by Django 3.2.12 on 2022-03-03 20:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectDataAPI', '0003_auto_20220303_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpagespecification',
            name='queryParams',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
