# Generated by Django 3.2.12 on 2022-06-13 06:38

from django.db import migrations, models


def assign_urls(apps, schema_editor):
    WebPageIdentifier = apps.get_model('CollectDataAPI', 'WebPageIdentifier')
    for identifier in WebPageIdentifier.objects.all():
        identifier.url = identifier.webPages.all().first().url
        identifier.save()


class Migration(migrations.Migration):
    dependencies = [
        ('CollectDataAPI', '0003_sequence_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpageidentifier',
            name='url',
            field=models.URLField(default=12, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webpageidentifier',
            name='similarityMethod',
            field=models.CharField(
                choices=[('1', 'MS'), ('2', 'APTED'), ('3', 'MS_Optimized'), ('4', 'APTED_Optimized')], default='3',
                max_length=2),
        ),
        migrations.RunPython(assign_urls),
    ]
