# Generated by Django 3.2.12 on 2022-04-12 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CollectDataAPI', '0003_alter_webpage_similarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='webPageIdentifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CollectDataAPI.webpageidentifier'),
        ),
    ]
