# Generated by Django 3.2.12 on 2022-04-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectDataAPI', '0003_remove_webpage_queryparams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
