# Generated by Django 3.2.12 on 2022-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectDataAPI', '0004_alter_webpage_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webPageIdentifier', models.ManyToManyField(to='CollectDataAPI.WebPageIdentifier')),
            ],
        ),
    ]
