# Generated by Django 3.2.12 on 2022-03-03 20:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectDataAPI', '0004_alter_webpagespecification_queryparams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpagespecification',
            name='queryParams',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None),
        ),
    ]
