# Generated by Django 3.2.12 on 2022-04-12 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CollectDataAPI', '0004_alter_webpage_webpageidentifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
