# Generated by Django 3.2.12 on 2022-03-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectDataAPI', '0005_alter_webpagespecification_queryparams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='pageStructure',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='webpagespecification',
            name='pageStructure',
            field=models.JSONField(),
        ),
    ]
